from .user import UserViewset
from .rolViewSet import RolViewSet
from .profesionViewSet import ProfesionViewSet
from .cursoViewSet import CursoViewSet
from .nivelViewSet import NivelViewSet
from .cicloViewSet import CicloViewSet
from .seccionViewSet import SeccionViewSet
from .gradoViewSet import GradoViewSet
from .catedraticoViewSet import CatedraticoViewSet
from .estudianteViewSet import EstudianteViewSet
from .asignacionViewSet import AsignacionViewSet
from .asignacionEstudianteViewSet import AsignacionEstudianteViewSet
from .materialViewSet import MaterialViewSet
from .tareaViewSet import TareaViewSet
from .tareaestudianteViewSet import TareaEstudianteViewSet
