# Generated by Django 2.2.13 on 2021-03-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaestudiante',
            name='documento_adjuntar',
            field=models.FileField(blank=True, null=True, upload_to='tareaestudiante'),
        ),
    ]
