# Generated by Django 2.2.13 on 2021-03-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210317_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareaestudiante',
            name='calificacion',
            field=models.FloatField(default=0),
        ),
    ]
