from .user import UserSerializer, UserReadSerializer, UserInfoSerializer
from .rolSerializer import RolSerializer, RolRegistroSerializer
from .profileSerializer import ProfileSerializer, ProfileRegistroSerializer
from .vendedorSerializer import VendedorSerializer, VendedorRegistroSerializer
from .productoSerializer import ProductoSerializer, ProductoRegistroSerializer
from .compraSerializer import CompraSerializer, CompraRegistroSerializer